name: Deploy Vite Project to GitHub Pages

on:
  push:
    branches:
      - master  # Vite projenizin ana branch'i

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  # GitHub deposunu kopyala

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Vite projenizin gereksinimleri için uygun Node.js sürümü

      - name: Install dependencies
        run: npm install  # Vite projenizin gereksinimlerini yükle

      - name: Build Vite Project
        run: npm run build  # Vite projenizi derle

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Vite projenizin çıktı klasörü
